# ----- Area Access ----- 
GARDEN_ACCESS = "Garden Access"
HIGH_STREET_ACCESS = "High Street Access"
BACK_GARDENS_ACCESS = "Back Gardens Access"
PUB_ACCESS = "Pub Access"
MODEL_VILLAGE_ACCESS = "Model Village Access"

PROGRESSIVE_AREA_ACCESS = "Progressive Area"

# ----- NPC Souls ----- 
NPC_GROUNDSKEEPER = "Groundskeeper's Soul"
NPC_BOY = "Boy's Soul"
NPC_TV_SHOP_OWNER = "TV Shop Owner's Soul"
NPC_MARKET_LADY = "Market Lady's Soul"
NPC_TIDY_NEIGHBOUR = "Tidy Neighbour's Soul"
NPC_MESSY_NEIGHBOUR = "Messy Neighbour's Soul"
NPC_BURLY_MAN = "Burly Man's Soul"
NPC_OLD_MAN = "Old Man's Soul"
NPC_PUB_LADY = "Pub Lady's Soul"
NPC_FANCY_LADIES = "Fancy Ladies' Souls"
NPC_COOK = "Cook's Soul"

# ----- Prop Essences ----- 

# Shared Areas
PROP_CARROTS = "Carrots"
PROP_PINT_BOTTLES = "Pint Bottles"
PROP_RIBBONS = "Ribbons"
PROP_TOMATOES = "Tomatoes"

# Starting Area/Hub
PROP_BOOTS = "Boots"
PROP_DRINK_CAN = "Drink Can"
PROP_DUMMY = "Dummy"
PROP_FISHING_BOBBER = "Fishing Bobber"
PROP_TACKLE_BOX = "Tackle Box"
PROP_TENNIS_BALL = "Tennis Ball"

# Garden
PROP_APPLES = "Apples"
PROP_CABBAGES = "Cabbages"
PROP_ESKY = "Esky"
PROP_GUMBOOTS = "Gumboots"
PROP_JAM = "Jam"
PROP_MALLET = "Mallet"
PROP_PICNIC_BASKET = "Picnic Basket"
PROP_PICNIC_MUG = "Picnic Mug"
PROP_PUMPKINS = "Pumpkins"
PROP_RADIO = "Radio"
PROP_RAKE = "Rake"
PROP_SANDWICH = "Sandwich"
PROP_SHOVEL = "Shovel"
PROP_STRAW_HAT = "Straw Hat"
PROP_THERMOS = "Thermos"
PROP_TOPSOIL_BAGS = "Topsoil Bags"
PROP_TROWEL = "Trowel"
PROP_TULIP = "Tulip"
PROP_WATERING_CAN = "Watering Can"
PROP_WOODEN_CRATE = "Wooden Crate"

# High Street
PROP_ADDING_MACHINE = "Adding Machine"
PROP_APPLE_CORES = "Apple Cores"
PROP_BABY_DOLL = "Baby Doll"
PROP_CHALK = "Chalk"
PROP_CUCUMBERS = "Cucumbers"
PROP_DISH_SOAP_BOTTLE = "Dish Soap Bottle"
PROP_DUSTBIN = "Dustbin"
PROP_DUSTBIN_LID = "Dustbin Lid"
PROP_FOOTBALL = "Football"
PROP_HAIRBRUSH = "Hairbrush"
PROP_HORN_RIMMED_GLASSES = "Horn-Rimmed Glasses"
PROP_LEEKS = "Leeks"
PROP_LILY_FLOWER = "Lily Flower"
PROP_LOO_PAPER = "Loo Paper"
PROP_ORANGES = "Oranges"
PROP_PRICING_GUN = "Pricing Gun"
PROP_PUSH_BROOM = "Push Broom"
PROP_RED_GLASSES = "Red Glasses"
PROP_SHOPPING_BASKET = "Shopping Basket"
PROP_SPRAY_BOTTLE = "Spray Bottle"
PROP_STEREOSCOPE = "Stereoscope"
PROP_SUNGLASSES = "Sunglasses"
PROP_TINNED_FOOD = "Tinned Food"
PROP_TOOTHRBRUSH = "Toothbrush"
PROP_TOY_CAR = "Toy Car"
PROP_TOY_PLANE = "Toy Plane"
PROP_UMBRELLAS = "Umbrellas"
PROP_WALKIE_TALKIES = "Walkie Talkies"
PROP_WEED_TOOLS = "Weed Tools"

# Back Gardens
PROP_BADMINTON_RACKET = "Badminton Racket"
PROP_BRA = "Bra"
PROP_BUST_GLASSES = "Bust Glasses"
PROP_BUST_HAT = "Bust Hat"
PROP_BUST_PIPE = "Bust Pipe"
PROP_CLIPPERS = "Clippers"
PROP_CRICKET_BALL = "Cricket Ball"
PROP_CRICKET_BAT = "Cricket Bat"
PROP_DRAWER = "Drawer"
PROP_DUCK_STATUE = "Duck Statue"
PROP_ENAMEL_JUG = "Enamel Jug"
PROP_FROG_STATUE = "Frog Statue"
PROP_JEREMY_FISH = "Jeremy Fish"
PROP_NEWSPAPER = "Newspaper"
PROP_NO_GOOSE_SIGN_CLEAN = "No Goose Sign (Clean)"
PROP_NO_GOOSE_SIGN_MESSY = "No Goose Sign (Messy)"
PROP_PAINTBRUSH = "Paintbrush"
PROP_POT_STACK = "Pot Stack"
PROP_ROSE = "Rose"
PROP_ROSE_BOX = "Rose Box"
PROP_SOAP = "Soap"
PROP_SOCKS = "Socks"
PROP_TEA_CUP = "Tea Cup"
PROP_TEA_POT = "Tea Pot"
PROP_VASE = "Vase"

# Pub
PROP_BUCKET = "Bucket"
PROP_CANDLESTICK = "Candlestick"
PROP_CORK = "Cork"
PROP_DARTBOARD = "Dartboard"
PROP_FLOWER_FOR_VASE = "Flower for Vase"
PROP_FORKS = "Forks"
PROP_GREEN_QUOITS = "Quoits (Green)"
PROP_HARMONICA = "Harmonica"
PROP_KNIVES = "Knives"
PROP_LETTER = "Letter"
PROP_MOP = "Mop"
PROP_MOP_BUCKET = "Mop Bucket"
PROP_NO_GOOSE_SIGN_PUB = "No Goose Sign (Pub)"
PROP_PARCEL = "Parcel"
PROP_PEPPER_GRINDER = "Pepper Grinder"
PROP_PINT_GLASSES = "Pint Glasses"
PROP_PLATES = "Plates"
PROP_PORTABLE_STOOL = "Portable Stool"
PROP_RED_QUOITS = "Quoits (Red)"
PROP_STEALTH_BOX = "Stealth Box"
PROP_TOY_BOAT = "Toy Boat"
PROP_TRAFFIC_CONE = "Traffic Cone"

# Model Village
PROP_GOLDEN_BELL = "Golden Bell"
PROP_MINI_BENCHES = "Miniature Benches"
PROP_MINI_BIRDBATH = "Miniature Birdbath"
PROP_MINI_EASEL = "Miniature Easel"
PROP_MINI_GOOSE = "Miniature Goose"
PROP_MINI_MAIL_PILLAR = "Miniature Mail Pillar"
PROP_MINI_PEOPLE = "Miniature People"
PROP_MINI_PHONE_DOOR = "Miniature Phone Door"
PROP_MINI_PUMP = "Miniature Pump"
PROP_MINI_SHOVEL = "Miniature Shovel"
PROP_MINI_SUN_LOUNGE = "Miniature Sun Lounge"
PROP_POPPY_FLOWER = "Poppy Flower"
PROP_TIMBER_HANDLE = "Timber Handle"

# ----- Filler -----
FILLER_MEGA_HONK = "Mega Honk"
FILLER_SPEEDY_FEET = "Speedy Feet"
FILLER_SILENT_STEPS = "Silent Steps"
FILLER_A_GOOSE_DAY = "A Goose Day"
FILLER_COIN = "Coin"

# ----- TRAPS -----
TRAP_TIRED_GOOSE = "Tired Goose"
TRAP_CONFUSED_FEET = "Confused Feet"
TRAP_BUTTERBEAK = "Butterbeak"
TRAP_SUSPICIOUS_GOOSE = "Suspicious Goose"

# ----- OTHER -----
ESCAPE_SEQUENCE = "Escape Sequence"