from typing import Dict, NamedTuple, Optional, Set
from BaseClasses import Item, ItemClassification

from .names import itemNames

class GooseGameItemData(NamedTuple):
    id: int
    classification: ItemClassification
    

class GooseGameItem(Item):
    game = "Untitled Goose Game"


BASE_ID = 119000000

item_table: Dict[str, GooseGameItemData] = {
    # Area Unlock Items (Progression)
    itemNames.GARDEN_ACCESS: GooseGameItemData(BASE_ID + 100, ItemClassification.progression),
    itemNames.HIGH_STREET_ACCESS: GooseGameItemData(BASE_ID + 101, ItemClassification.progression),
    itemNames.BACK_GARDENS_ACCESS: GooseGameItemData(BASE_ID + 102, ItemClassification.progression),
    itemNames.PUB_ACCESS: GooseGameItemData(BASE_ID + 103, ItemClassification.progression),
    itemNames.MODEL_VILLAGE_ACCESS: GooseGameItemData(BASE_ID + 104, ItemClassification.progression),
    
    # Progressive Area (alternative)
    itemNames.PROGRESSIVE_AREA_ACCESS: GooseGameItemData(BASE_ID + 110, ItemClassification.progression),
    
    # === NPC Souls (Progression) - NPCs won't appear until you have their soul ===
    itemNames.NPC_GROUNDSKEEPER: GooseGameItemData(BASE_ID + 120, ItemClassification.progression),
    itemNames.NPC_BOY: GooseGameItemData(BASE_ID + 121, ItemClassification.progression),
    itemNames.NPC_TV_SHOP_OWNER: GooseGameItemData(BASE_ID + 122, ItemClassification.progression),
    itemNames.NPC_MARKET_LADY: GooseGameItemData(BASE_ID + 123, ItemClassification.progression),
    itemNames.NPC_TIDY_NEIGHBOUR: GooseGameItemData(BASE_ID + 124, ItemClassification.progression),
    itemNames.NPC_MESSY_NEIGHBOUR: GooseGameItemData(BASE_ID + 125, ItemClassification.progression),
    itemNames.NPC_BURLY_MAN: GooseGameItemData(BASE_ID + 126, ItemClassification.progression),
    itemNames.NPC_OLD_MAN: GooseGameItemData(BASE_ID + 127, ItemClassification.progression),
    itemNames.NPC_PUB_LADY: GooseGameItemData(BASE_ID + 128, ItemClassification.progression),
    itemNames.NPC_FANCY_LADIES: GooseGameItemData(BASE_ID + 129, ItemClassification.progression),
    itemNames.NPC_COOK: GooseGameItemData(BASE_ID + 130, ItemClassification.progression),
    
    # === GROUPED PROP SOULS (IDs 400-499) - Multiple instances share one soul ===
    itemNames.PROP_CARROTS: GooseGameItemData(BASE_ID + 400, ItemClassification.progression),
    itemNames.PROP_TOMATOES: GooseGameItemData(BASE_ID + 401, ItemClassification.progression),
    itemNames.PROP_PUMPKINS: GooseGameItemData(BASE_ID + 402, ItemClassification.progression),
    itemNames.PROP_TOPSOIL_BAGS: GooseGameItemData(BASE_ID + 403, ItemClassification.progression),
    itemNames.PROP_GREEN_QUOITS: GooseGameItemData(BASE_ID + 404, ItemClassification.progression),
    itemNames.PROP_PLATES: GooseGameItemData(BASE_ID + 405, ItemClassification.progression),
    itemNames.PROP_ORANGES: GooseGameItemData(BASE_ID + 406, ItemClassification.progression),
    itemNames.PROP_LEEKS: GooseGameItemData(BASE_ID + 407, ItemClassification.progression),
    itemNames.PROP_CUCUMBERS: GooseGameItemData(BASE_ID + 408, ItemClassification.progression),
    itemNames.PROP_RED_QUOITS: GooseGameItemData(BASE_ID + 409, ItemClassification.progression),
    itemNames.PROP_UMBRELLAS: GooseGameItemData(BASE_ID + 410, ItemClassification.progression),
    itemNames.PROP_TINNED_FOOD: GooseGameItemData(BASE_ID + 411, ItemClassification.progression),
    itemNames.PROP_SOCKS: GooseGameItemData(BASE_ID + 412, ItemClassification.progression),
    itemNames.PROP_PINT_BOTTLES: GooseGameItemData(BASE_ID + 413, ItemClassification.progression),
    itemNames.PROP_KNIVES: GooseGameItemData(BASE_ID + 414, ItemClassification.progression),
    itemNames.PROP_GUMBOOTS: GooseGameItemData(BASE_ID + 415, ItemClassification.progression),
    itemNames.PROP_FORKS: GooseGameItemData(BASE_ID + 416, ItemClassification.progression),
    itemNames.PROP_APPLE_CORES: GooseGameItemData(BASE_ID + 418, ItemClassification.progression),
    itemNames.PROP_APPLES: GooseGameItemData(BASE_ID + 419, ItemClassification.progression),
    itemNames.PROP_SANDWICH: GooseGameItemData(BASE_ID + 420, ItemClassification.progression),
    itemNames.PROP_RIBBONS: GooseGameItemData(BASE_ID + 422, ItemClassification.progression),
    itemNames.PROP_WALKIE_TALKIES: GooseGameItemData(BASE_ID + 423, ItemClassification.progression),
    itemNames.PROP_BOOTS: GooseGameItemData(BASE_ID + 424, ItemClassification.progression),
    itemNames.PROP_MINI_PEOPLE: GooseGameItemData(BASE_ID + 425, ItemClassification.progression),
    itemNames.PROP_MINI_BENCHES: GooseGameItemData(BASE_ID + 617, ItemClassification.progression),
    itemNames.PROP_WEED_TOOLS: GooseGameItemData(BASE_ID + 531, ItemClassification.progression),
    
    # === GARDEN ONE-OFF PROP SOULS (IDs 500-519) ===
    itemNames.PROP_RADIO: GooseGameItemData(BASE_ID + 500, ItemClassification.progression),
    itemNames.PROP_CABBAGES: GooseGameItemData(BASE_ID + 502, ItemClassification.progression_deprioritized),
    itemNames.PROP_TROWEL: GooseGameItemData(BASE_ID + 501, ItemClassification.progression),
    itemNames.PROP_TULIP: GooseGameItemData(BASE_ID + 503, ItemClassification.progression),
    itemNames.PROP_JAM: GooseGameItemData(BASE_ID + 504, ItemClassification.progression),
    itemNames.PROP_PICNIC_MUG: GooseGameItemData(BASE_ID + 505, ItemClassification.progression_deprioritized),
    itemNames.PROP_THERMOS: GooseGameItemData(BASE_ID + 506, ItemClassification.progression),
    itemNames.PROP_STRAW_HAT: GooseGameItemData(BASE_ID + 507, ItemClassification.progression),
    itemNames.PROP_DRINK_CAN: GooseGameItemData(BASE_ID + 508, ItemClassification.progression_deprioritized),
    itemNames.PROP_TENNIS_BALL: GooseGameItemData(BASE_ID + 509, ItemClassification.progression_deprioritized),
    itemNames.PROP_RAKE: GooseGameItemData(BASE_ID + 511, ItemClassification.progression),
    itemNames.PROP_PICNIC_BASKET: GooseGameItemData(BASE_ID + 512, ItemClassification.progression),
    itemNames.PROP_ESKY: GooseGameItemData(BASE_ID + 513, ItemClassification.progression_deprioritized),
    itemNames.PROP_SHOVEL: GooseGameItemData(BASE_ID + 514, ItemClassification.progression_deprioritized),
    itemNames.PROP_WATERING_CAN: GooseGameItemData(BASE_ID + 515, ItemClassification.progression_deprioritized),
    itemNames.PROP_MALLET: GooseGameItemData(BASE_ID + 517, ItemClassification.progression),
    itemNames.PROP_WOODEN_CRATE: GooseGameItemData(BASE_ID + 518, ItemClassification.progression_deprioritized),
    
    # === HIGH STREET ONE-OFF PROP SOULS (IDs 520-549) ===
    itemNames.PROP_HORN_RIMMED_GLASSES: GooseGameItemData(BASE_ID + 521, ItemClassification.progression),
    itemNames.PROP_RED_GLASSES: GooseGameItemData(BASE_ID + 522, ItemClassification.progression),
    itemNames.PROP_SUNGLASSES: GooseGameItemData(BASE_ID + 523, ItemClassification.progression),
    itemNames.PROP_LOO_PAPER: GooseGameItemData(BASE_ID + 524, ItemClassification.progression),
    itemNames.PROP_TOY_CAR: GooseGameItemData(BASE_ID + 525, ItemClassification.progression_deprioritized),
    itemNames.PROP_HAIRBRUSH: GooseGameItemData(BASE_ID + 526, ItemClassification.progression),
    itemNames.PROP_TOOTHRBRUSH: GooseGameItemData(BASE_ID + 527, ItemClassification.progression),
    itemNames.PROP_STEREOSCOPE: GooseGameItemData(BASE_ID + 528, ItemClassification.progression),
    itemNames.PROP_DISH_SOAP_BOTTLE: GooseGameItemData(BASE_ID + 529, ItemClassification.progression),
    itemNames.PROP_SPRAY_BOTTLE: GooseGameItemData(BASE_ID + 530, ItemClassification.progression),
    itemNames.PROP_LILY_FLOWER: GooseGameItemData(BASE_ID + 532, ItemClassification.progression),
    itemNames.PROP_TOY_PLANE: GooseGameItemData(BASE_ID + 533, ItemClassification.progression),
    itemNames.PROP_FOOTBALL: GooseGameItemData(BASE_ID + 534, ItemClassification.progression),
    itemNames.PROP_CHALK: GooseGameItemData(BASE_ID + 535, ItemClassification.progression),
    itemNames.PROP_DUSTBIN_LID: GooseGameItemData(BASE_ID + 536, ItemClassification.progression_deprioritized),
    itemNames.PROP_SHOPPING_BASKET: GooseGameItemData(BASE_ID + 537, ItemClassification.progression),
    itemNames.PROP_PUSH_BROOM: GooseGameItemData(BASE_ID + 538, ItemClassification.progression),
    itemNames.PROP_GARAGE_ROPE: GooseGameItemData(BASE_ID + 539, ItemClassification.progression),
    itemNames.PROP_DUSTBIN: GooseGameItemData(BASE_ID + 540, ItemClassification.progression_deprioritized),
    itemNames.PROP_BABY_DOLL: GooseGameItemData(BASE_ID + 541, ItemClassification.progression_deprioritized),
    itemNames.PROP_PRICING_GUN: GooseGameItemData(BASE_ID + 542, ItemClassification.progression_deprioritized),
    itemNames.PROP_ADDING_MACHINE: GooseGameItemData(BASE_ID + 543, ItemClassification.progression_deprioritized),
    
    # === BACK GARDENS ONE-OFF PROP SOULS (IDs 550-579) ===
    itemNames.PROP_DUMMY: GooseGameItemData(BASE_ID + 550, ItemClassification.progression_deprioritized),
    itemNames.PROP_CRICKET_BALL: GooseGameItemData(BASE_ID + 551, ItemClassification.progression_deprioritized),
    itemNames.PROP_BUST_PIPE: GooseGameItemData(BASE_ID + 552, ItemClassification.progression),
    itemNames.PROP_BUST_HAT: GooseGameItemData(BASE_ID + 553, ItemClassification.progression),
    itemNames.PROP_BUST_GLASSES: GooseGameItemData(BASE_ID + 554, ItemClassification.progression),
    itemNames.PROP_TEA_CUP: GooseGameItemData(BASE_ID + 555, ItemClassification.progression),
    itemNames.PROP_NEWSPAPER: GooseGameItemData(BASE_ID + 556, ItemClassification.progression_deprioritized),
    itemNames.PROP_BADMINTON_RACKET: GooseGameItemData(BASE_ID + 557, ItemClassification.progression_deprioritized),
    itemNames.PROP_POT_STACK: GooseGameItemData(BASE_ID + 558, ItemClassification.progression_deprioritized),
    itemNames.PROP_SOAP: GooseGameItemData(BASE_ID + 559, ItemClassification.progression),
    itemNames.PROP_PAINTBRUSH: GooseGameItemData(BASE_ID + 560, ItemClassification.progression),
    itemNames.PROP_VASE: GooseGameItemData(BASE_ID + 561, ItemClassification.progression),
    itemNames.PROP_BRA: GooseGameItemData(BASE_ID + 562, ItemClassification.progression),
    itemNames.PROP_ROSE: GooseGameItemData(BASE_ID + 563, ItemClassification.progression),
    itemNames.PROP_ROSE_BOX: GooseGameItemData(BASE_ID + 564, ItemClassification.progression),
    itemNames.PROP_CRICKET_BAT: GooseGameItemData(BASE_ID + 565, ItemClassification.progression_deprioritized),
    itemNames.PROP_TEA_POT: GooseGameItemData(BASE_ID + 566, ItemClassification.progression_deprioritized),
    itemNames.PROP_CLIPPERS: GooseGameItemData(BASE_ID + 567, ItemClassification.progression),
    itemNames.PROP_DUCK_STATUE: GooseGameItemData(BASE_ID + 568, ItemClassification.progression),
    itemNames.PROP_FROG_STATUE: GooseGameItemData(BASE_ID + 569, ItemClassification.progression_deprioritized),
    itemNames.PROP_JEREMY_FISH: GooseGameItemData(BASE_ID + 570, ItemClassification.progression_deprioritized),
    itemNames.PROP_NO_GOOSE_SIGN_MESSY: GooseGameItemData(BASE_ID + 571, ItemClassification.progression),
    itemNames.PROP_DRAWER: GooseGameItemData(BASE_ID + 572, ItemClassification.progression),
    itemNames.PROP_ENAMEL_JUG: GooseGameItemData(BASE_ID + 573, ItemClassification.progression_deprioritized),
    itemNames.PROP_NO_GOOSE_SIGN_CLEAN: GooseGameItemData(BASE_ID + 574, ItemClassification.progression),
    
    # === PUB ONE-OFF PROP SOULS (IDs 580-609) ===
    itemNames.PROP_FISHING_BOBBER: GooseGameItemData(BASE_ID + 580, ItemClassification.progression_deprioritized),
    itemNames.PROP_LETTER: GooseGameItemData(BASE_ID + 581, ItemClassification.progression_deprioritized),
    itemNames.PROP_PINT_GLASSES: GooseGameItemData(BASE_ID + 582, ItemClassification.progression),
    itemNames.PROP_TOY_BOAT: GooseGameItemData(BASE_ID + 583, ItemClassification.progression),
    itemNames.PROP_PEPPER_GRINDER: GooseGameItemData(BASE_ID + 585, ItemClassification.progression),
    itemNames.PROP_CORK: GooseGameItemData(BASE_ID + 587, ItemClassification.progression_deprioritized),
    itemNames.PROP_CANDLESTICK: GooseGameItemData(BASE_ID + 588, ItemClassification.progression),
    itemNames.PROP_FLOWER_FOR_VASE: GooseGameItemData(BASE_ID + 589, ItemClassification.progression),
    itemNames.PROP_HARMONICA: GooseGameItemData(BASE_ID + 590, ItemClassification.progression),
    itemNames.PROP_TACKLE_BOX: GooseGameItemData(BASE_ID + 591, ItemClassification.progression_deprioritized),
    itemNames.PROP_TRAFFIC_CONE: GooseGameItemData(BASE_ID + 592, ItemClassification.progression),
    itemNames.PROP_PARCEL: GooseGameItemData(BASE_ID + 593, ItemClassification.progression_deprioritized),
    itemNames.PROP_STEALTH_BOX: GooseGameItemData(BASE_ID + 594, ItemClassification.progression),
    itemNames.PROP_NO_GOOSE_SIGN_PUB: GooseGameItemData(BASE_ID + 595, ItemClassification.progression),
    itemNames.PROP_PORTABLE_STOOL: GooseGameItemData(BASE_ID + 596, ItemClassification.progression),
    itemNames.PROP_DARTBOARD: GooseGameItemData(BASE_ID + 597, ItemClassification.progression),
    itemNames.PROP_MOP_BUCKET: GooseGameItemData(BASE_ID + 598, ItemClassification.progression_deprioritized),
    itemNames.PROP_MOP: GooseGameItemData(BASE_ID + 599, ItemClassification.progression_deprioritized),
    itemNames.PROP_BUCKET: GooseGameItemData(BASE_ID + 601, ItemClassification.progression),
    
    # === MODEL VILLAGE ONE-OFF PROP SOULS (IDs 610-629) ===
    itemNames.PROP_MINI_MAIL_PILLAR: GooseGameItemData(BASE_ID + 610, ItemClassification.progression_deprioritized),
    itemNames.PROP_MINI_PHONE_DOOR: GooseGameItemData(BASE_ID + 611, ItemClassification.progression_deprioritized),
    itemNames.PROP_MINI_SHOVEL: GooseGameItemData(BASE_ID + 612, ItemClassification.progression_deprioritized),
    itemNames.PROP_POPPY_FLOWER: GooseGameItemData(BASE_ID + 613, ItemClassification.progression_deprioritized),
    itemNames.PROP_TIMBER_HANDLE: GooseGameItemData(BASE_ID + 614, ItemClassification.progression),
    itemNames.PROP_MINI_BIRDBATH: GooseGameItemData(BASE_ID + 615, ItemClassification.progression_deprioritized),
    itemNames.PROP_MINI_EASEL: GooseGameItemData(BASE_ID + 616, ItemClassification.progression_deprioritized),
    itemNames.PROP_MINI_PUMP: GooseGameItemData(BASE_ID + 618, ItemClassification.progression_deprioritized),
    itemNames.PROP_MINI_GOOSE: GooseGameItemData(BASE_ID + 619, ItemClassification.progression_deprioritized),
    itemNames.PROP_MINI_SUN_LOUNGE: GooseGameItemData(BASE_ID + 620, ItemClassification.progression_deprioritized),
    
    # Victory item soul
    itemNames.PROP_GOLDEN_BELL: GooseGameItemData(BASE_ID + 621, ItemClassification.progression),
    
    # === FILLER ITEMS ===
    itemNames.FILLER_MEGA_HONK: GooseGameItemData(BASE_ID + 200, ItemClassification.useful),
    itemNames.FILLER_SPEEDY_FEET: GooseGameItemData(BASE_ID + 201, ItemClassification.useful),
    itemNames.FILLER_SILENT_STEPS: GooseGameItemData(BASE_ID + 202, ItemClassification.useful),
    itemNames.FILLER_A_GOOSE_DAY: GooseGameItemData(BASE_ID + 203, ItemClassification.filler),
    itemNames.FILLER_COIN: GooseGameItemData(BASE_ID + 204, ItemClassification.filler),
    
    # === TRAP ITEMS ===
    itemNames.TRAP_TIRED_GOOSE: GooseGameItemData(BASE_ID + 300, ItemClassification.trap),
    itemNames.TRAP_CONFUSED_FEET: GooseGameItemData(BASE_ID + 301, ItemClassification.trap),
    itemNames.TRAP_BUTTERBEAK: GooseGameItemData(BASE_ID + 302, ItemClassification.trap),
    itemNames.TRAP_SUSPICIOUS_GOOSE: GooseGameItemData(BASE_ID + 303, ItemClassification.trap),
    
    # Victory
    
    itemNames.ESCAPE_SEQUENCE: GooseGameItemData(BASE_ID + 999, ItemClassification.progression),

}

# Item groups for logical grouping
ITEM_GROUPS = {
    "Area Unlocks": {
        itemNames.GARDEN_ACCESS,
        itemNames.HIGH_STREET_ACCESS,
        itemNames.BACK_GARDENS_ACCESS,
        itemNames.PUB_ACCESS,
        itemNames.MODEL_VILLAGE_ACCESS,
    },
    "NPC Souls": {
        itemNames.NPC_GROUNDSKEEPER,
        itemNames.NPC_BOY,
        itemNames.NPC_TV_SHOP_OWNER,
        itemNames.NPC_MARKET_LADY,
        itemNames.NPC_TIDY_NEIGHBOUR,
        itemNames.NPC_MESSY_NEIGHBOUR,
        itemNames.NPC_BURLY_MAN,
        itemNames.NPC_OLD_MAN,
        itemNames.NPC_PUB_LADY,
        itemNames.NPC_FANCY_LADIES,
        itemNames.NPC_COOK,
    },
    "Grouped Props": {
        itemNames.PROP_CARROTS,
        itemNames.PROP_TOMATOES,
        itemNames.PROP_PUMPKINS,
        itemNames.PROP_TOPSOIL_BAGS,
        itemNames.PROP_GREEN_QUOITS,
        itemNames.PROP_PLATES,
        itemNames.PROP_ORANGES,
        itemNames.PROP_LEEKS,
        itemNames.PROP_CUCUMBERS,
        itemNames.PROP_UMBRELLAS,
        itemNames.PROP_TINNED_FOOD,
        itemNames.PROP_SOCKS,
        itemNames.PROP_PINT_BOTTLES,
        itemNames.PROP_KNIVES,
        itemNames.PROP_GUMBOOTS,
        itemNames.PROP_FORKS,
        itemNames.PROP_APPLE_CORES,
        itemNames.PROP_APPLES,
        itemNames.PROP_SANDWICH,
        itemNames.PROP_RED_QUOITS,
        itemNames.PROP_RIBBONS,
        itemNames.PROP_WALKIE_TALKIES,
        itemNames.PROP_BOOTS,
        itemNames.PROP_MINI_PEOPLE,
        itemNames.PROP_MINI_BENCHES,
        itemNames.PROP_WEED_TOOLS,
    },
    "Start or Hub Props": {
        itemNames.PROP_PINT_BOTTLES,
        itemNames.PROP_BOOTS,
        itemNames.PROP_DRINK_CAN,
        itemNames.PROP_TENNIS_BALL,
        itemNames.PROP_DUMMY,
        itemNames.PROP_FISHING_BOBBER,
        itemNames.PROP_TACKLE_BOX,
        itemNames.PROP_RIBBONS,
    },
    "Garden One-Off Props": {
        itemNames.PROP_RADIO,
        itemNames.PROP_TROWEL,
        itemNames.PROP_TULIP,
        itemNames.PROP_JAM,
        itemNames.PROP_PICNIC_MUG,
        itemNames.PROP_THERMOS,
        itemNames.PROP_STRAW_HAT,
        itemNames.PROP_RAKE,
        itemNames.PROP_PICNIC_BASKET,
        itemNames.PROP_ESKY,
        itemNames.PROP_SHOVEL,
        itemNames.PROP_WATERING_CAN,
        itemNames.PROP_MALLET,
        itemNames.PROP_WOODEN_CRATE,
    },
    "Garden Props": {
        itemNames.PROP_RADIO,
        itemNames.PROP_TROWEL,
        itemNames.PROP_TULIP,
        itemNames.PROP_JAM,
        itemNames.PROP_PICNIC_MUG,
        itemNames.PROP_THERMOS,
        itemNames.PROP_STRAW_HAT,
        itemNames.PROP_RAKE,
        itemNames.PROP_PICNIC_BASKET,
        itemNames.PROP_ESKY,
        itemNames.PROP_SHOVEL,
        itemNames.PROP_WATERING_CAN,
        itemNames.PROP_MALLET,
        itemNames.PROP_WOODEN_CRATE,
        itemNames.PROP_CARROTS,
        itemNames.PROP_PUMPKINS,
        itemNames.PROP_TOPSOIL_BAGS,
        itemNames.PROP_GUMBOOTS,
        itemNames.PROP_APPLES,
        itemNames.PROP_SANDWICH,
    },
    "High Street One-Off Props": {
        itemNames.PROP_HORN_RIMMED_GLASSES,
        itemNames.PROP_RED_GLASSES,
        itemNames.PROP_SUNGLASSES,
        itemNames.PROP_LOO_PAPER,
        itemNames.PROP_TOY_CAR,
        itemNames.PROP_HAIRBRUSH,
        itemNames.PROP_TOOTHRBRUSH,
        itemNames.PROP_STEREOSCOPE,
        itemNames.PROP_DISH_SOAP_BOTTLE,
        itemNames.PROP_SPRAY_BOTTLE,
        itemNames.PROP_LILY_FLOWER,
        itemNames.PROP_TOY_PLANE,
        itemNames.PROP_CHALK,
        itemNames.PROP_DUSTBIN_LID,
        itemNames.PROP_SHOPPING_BASKET,
        itemNames.PROP_PUSH_BROOM,
        itemNames.PROP_DUSTBIN,
        itemNames.PROP_BABY_DOLL,
        itemNames.PROP_PRICING_GUN,
        itemNames.PROP_ADDING_MACHINE,
    },
    "High Street Props": {
        itemNames.PROP_HORN_RIMMED_GLASSES,
        itemNames.PROP_RED_GLASSES,
        itemNames.PROP_SUNGLASSES,
        itemNames.PROP_LOO_PAPER,
        itemNames.PROP_TOY_CAR,
        itemNames.PROP_HAIRBRUSH,
        itemNames.PROP_TOOTHRBRUSH,
        itemNames.PROP_STEREOSCOPE,
        itemNames.PROP_DISH_SOAP_BOTTLE,
        itemNames.PROP_SPRAY_BOTTLE,
        itemNames.PROP_LILY_FLOWER,
        itemNames.PROP_TOY_PLANE,
        itemNames.PROP_CHALK,
        itemNames.PROP_DUSTBIN_LID,
        itemNames.PROP_SHOPPING_BASKET,
        itemNames.PROP_PUSH_BROOM,
        itemNames.PROP_DUSTBIN,
        itemNames.PROP_BABY_DOLL,
        itemNames.PROP_PRICING_GUN,
        itemNames.PROP_ADDING_MACHINE,
        itemNames.PROP_CARROTS,
        itemNames.PROP_TOMATOES,
        itemNames.PROP_ORANGES,
        itemNames.PROP_LEEKS,
        itemNames.PROP_CUCUMBERS,
        itemNames.PROP_UMBRELLAS,
        itemNames.PROP_TINNED_FOOD,
        itemNames.PROP_PINT_BOTTLES,
        itemNames.PROP_APPLE_CORES,
        itemNames.PROP_WALKIE_TALKIES,
        itemNames.PROP_WEED_TOOLS,
    },
    "Back Gardens One-Off Props": {
        itemNames.PROP_CRICKET_BALL,
        itemNames.PROP_BUST_PIPE,
        itemNames.PROP_BUST_HAT,
        itemNames.PROP_BUST_GLASSES,
        itemNames.PROP_TEA_CUP,
        itemNames.PROP_NEWSPAPER,
        itemNames.PROP_BADMINTON_RACKET,
        itemNames.PROP_POT_STACK,
        itemNames.PROP_SOAP,
        itemNames.PROP_PAINTBRUSH,
        itemNames.PROP_VASE,
        itemNames.PROP_BRA,
        itemNames.PROP_ROSE,
        itemNames.PROP_ROSE_BOX,
        itemNames.PROP_CRICKET_BAT,
        itemNames.PROP_TEA_POT,
        itemNames.PROP_CLIPPERS,
        itemNames.PROP_DUCK_STATUE,
        itemNames.PROP_FROG_STATUE,
        itemNames.PROP_JEREMY_FISH,
        itemNames.PROP_NO_GOOSE_SIGN_MESSY,
        itemNames.PROP_DRAWER,
        itemNames.PROP_ENAMEL_JUG,
        itemNames.PROP_NO_GOOSE_SIGN_CLEAN,
    },
    "Back Gardens Props": {
        itemNames.PROP_CRICKET_BALL,
        itemNames.PROP_BUST_PIPE,
        itemNames.PROP_BUST_HAT,
        itemNames.PROP_BUST_GLASSES,
        itemNames.PROP_TEA_CUP,
        itemNames.PROP_NEWSPAPER,
        itemNames.PROP_BADMINTON_RACKET,
        itemNames.PROP_POT_STACK,
        itemNames.PROP_SOAP,
        itemNames.PROP_PAINTBRUSH,
        itemNames.PROP_VASE,
        itemNames.PROP_BRA,
        itemNames.PROP_ROSE,
        itemNames.PROP_ROSE_BOX,
        itemNames.PROP_CRICKET_BAT,
        itemNames.PROP_TEA_POT,
        itemNames.PROP_CLIPPERS,
        itemNames.PROP_DUCK_STATUE,
        itemNames.PROP_FROG_STATUE,
        itemNames.PROP_JEREMY_FISH,
        itemNames.PROP_NO_GOOSE_SIGN_MESSY,
        itemNames.PROP_DRAWER,
        itemNames.PROP_ENAMEL_JUG,
        itemNames.PROP_NO_GOOSE_SIGN_CLEAN,
        itemNames.PROP_SOCKS,
        itemNames.PROP_RIBBONS,
    },
    "Pub One-Off Props": {
        itemNames.PROP_LETTER,
        itemNames.PROP_PINT_GLASSES,
        itemNames.PROP_TOY_BOAT,
        itemNames.PROP_PEPPER_GRINDER,
        itemNames.PROP_CORK,
        itemNames.PROP_CANDLESTICK,
        itemNames.PROP_FLOWER_FOR_VASE,
        itemNames.PROP_HARMONICA,
        itemNames.PROP_TRAFFIC_CONE,
        itemNames.PROP_PARCEL,
        itemNames.PROP_STEALTH_BOX,
        itemNames.PROP_NO_GOOSE_SIGN_PUB,
        itemNames.PROP_PORTABLE_STOOL,
        itemNames.PROP_DARTBOARD,
        itemNames.PROP_MOP_BUCKET,
        itemNames.PROP_MOP,
        itemNames.PROP_BUCKET,
    },
    "Pub Props": {
        itemNames.PROP_LETTER,
        itemNames.PROP_PINT_GLASSES,
        itemNames.PROP_TOY_BOAT,
        itemNames.PROP_PEPPER_GRINDER,
        itemNames.PROP_CORK,
        itemNames.PROP_CANDLESTICK,
        itemNames.PROP_FLOWER_FOR_VASE,
        itemNames.PROP_GREEN_QUOITS,
        itemNames.PROP_HARMONICA,
        itemNames.PROP_TRAFFIC_CONE,
        itemNames.PROP_PARCEL,
        itemNames.PROP_STEALTH_BOX,
        itemNames.PROP_NO_GOOSE_SIGN_PUB,
        itemNames.PROP_PORTABLE_STOOL,
        itemNames.PROP_DARTBOARD,
        itemNames.PROP_MOP_BUCKET,
        itemNames.PROP_MOP,
        itemNames.PROP_BUCKET,
        itemNames.PROP_RED_QUOITS,
        itemNames.PROP_TOMATOES,
        itemNames.PROP_PLATES,
        itemNames.PROP_KNIVES,
        itemNames.PROP_FORKS,
    },
    "Model Village One-Off Props": {
        itemNames.PROP_MINI_GOOSE,
        itemNames.PROP_MINI_MAIL_PILLAR,
        itemNames.PROP_MINI_PHONE_DOOR,
        itemNames.PROP_MINI_SHOVEL,
        itemNames.PROP_POPPY_FLOWER,
        itemNames.PROP_TIMBER_HANDLE,
        itemNames.PROP_MINI_BIRDBATH,
        itemNames.PROP_MINI_EASEL,
        itemNames.PROP_MINI_PUMP,
        itemNames.PROP_MINI_SUN_LOUNGE,
    },
    "Model Village Props": {
        itemNames.PROP_MINI_GOOSE,
        itemNames.PROP_MINI_MAIL_PILLAR,
        itemNames.PROP_MINI_PHONE_DOOR,
        itemNames.PROP_MINI_SHOVEL,
        itemNames.PROP_POPPY_FLOWER,
        itemNames.PROP_TIMBER_HANDLE,
        itemNames.PROP_MINI_BIRDBATH,
        itemNames.PROP_MINI_EASEL,
        itemNames.PROP_MINI_PUMP,
        itemNames.PROP_MINI_SUN_LOUNGE,
        itemNames.PROP_MINI_PEOPLE,
        itemNames.PROP_MINI_BENCHES,
    },
    "Fillers": {
        itemNames.FILLER_MEGA_HONK,
        itemNames.FILLER_SPEEDY_FEET,
        itemNames.FILLER_SILENT_STEPS,
        itemNames.FILLER_A_GOOSE_DAY,
        itemNames.FILLER_COIN,
    },
    "Traps": {
        itemNames.TRAP_TIRED_GOOSE,
        itemNames.TRAP_CONFUSED_FEET,
        itemNames.TRAP_BUTTERBEAK,
        itemNames.TRAP_SUSPICIOUS_GOOSE,
    },
    "Main Task Progression Props": {
        itemNames.PROP_RADIO,
        itemNames.PROP_TULIP,
        itemNames.PROP_JAM,
        itemNames.PROP_THERMOS,
        itemNames.PROP_STRAW_HAT,
        itemNames.PROP_RAKE,
        itemNames.PROP_PICNIC_BASKET,
        itemNames.PROP_MALLET,
        itemNames.PROP_CARROTS,
        itemNames.PROP_PUMPKINS,
        itemNames.PROP_APPLES,
        itemNames.PROP_SANDWICH,
        itemNames.PROP_HORN_RIMMED_GLASSES,
        itemNames.PROP_RED_GLASSES,
        itemNames.PROP_SUNGLASSES,
        itemNames.PROP_LOO_PAPER,
        itemNames.PROP_HAIRBRUSH,
        itemNames.PROP_TOOTHRBRUSH,
        itemNames.PROP_DISH_SOAP_BOTTLE,
        itemNames.PROP_SPRAY_BOTTLE,
        itemNames.PROP_CHALK,
        itemNames.PROP_SHOPPING_BASKET,
        itemNames.PROP_PUSH_BROOM,
        itemNames.PROP_TOMATOES,
        itemNames.PROP_ORANGES,
        itemNames.PROP_LEEKS,
        itemNames.PROP_CUCUMBERS,
        itemNames.PROP_TINNED_FOOD,
        itemNames.PROP_BUST_PIPE,
        itemNames.PROP_BUST_HAT,
        itemNames.PROP_BUST_GLASSES,
        itemNames.PROP_TEA_CUP,
        itemNames.PROP_SOAP,
        itemNames.PROP_VASE,
        itemNames.PROP_BRA,
        itemNames.PROP_ROSE,
        itemNames.PROP_ROSE_BOX,
        itemNames.PROP_CLIPPERS,
        itemNames.PROP_DUCK_STATUE,
        itemNames.PROP_NO_GOOSE_SIGN_MESSY,
        itemNames.PROP_DRAWER,
        itemNames.PROP_NO_GOOSE_SIGN_CLEAN,
        itemNames.PROP_SOCKS,
        itemNames.PROP_RIBBONS,
        itemNames.PROP_PINT_GLASSES,
        itemNames.PROP_TOY_BOAT,
        itemNames.PROP_PEPPER_GRINDER,
        itemNames.PROP_CANDLESTICK,
        itemNames.PROP_FLOWER_FOR_VASE,
        itemNames.PROP_NO_GOOSE_SIGN_PUB,
        itemNames.PROP_PORTABLE_STOOL,
        itemNames.PROP_DARTBOARD,
        itemNames.PROP_BUCKET,
        itemNames.PROP_PLATES,
        itemNames.PROP_KNIVES,
        itemNames.PROP_FORKS,
        itemNames.PROP_TIMBER_HANDLE,
    },
}